database:
  username: root
  password: 'password'
  path: '127.0.0.1:3306'
  db-name: 'tgo'
  config: 'charset=utf8&parseTime=True&loc=Local'
  max-idle-conns: 10
  max-open-conns: 10
  log-mode: true


redis:
  addr: '127.0.0.1:6379'
  password: ''
  db: 0